name: movie_locator
description: "Movie Discovery App - Find and explore movies and TV shows"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # UI & Icons
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10+1
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  lottie: ^3.1.2

  # State Management
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5

  # HTTP & API
  dio: ^5.4.3+1
  retrofit: ^4.1.0
  json_annotation: ^4.8.1

  # Local Storage
  drift: ^2.18.0
  drift_flutter: ^0.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.2.3
  flutter_secure_storage: ^9.2.2

  # Dependency Injection
  get_it: ^7.6.7
  injectable: ^2.4.1

  # Navigation
  go_router: ^14.2.7

  # Utils
  dartz: ^0.10.1
  connectivity_plus: ^6.0.5
  path_provider: ^2.1.3
  path: ^1.9.0
  intl: ^0.19.0

  # Environment
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  # Code Generation
  build_runner: ^2.4.9
  json_serializable: ^6.8.0
  retrofit_generator: ^8.1.0
  injectable_generator: ^2.6.2
  drift_dev: ^2.18.0

  # Testing
  mockito: ^5.4.4
  bloc_test: ^9.1.7
  integration_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
    - .env

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
