// Mocks generated by Mockito 5.4.5 from annotations
// in movie_locator/test/features/movies/presentation/bloc/movies_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:dartz/dartz.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:movie_locator/core/errors/failures.dart' as _i6;
import 'package:movie_locator/features/movies/domain/entities/genre.dart'
    as _i12;
import 'package:movie_locator/features/movies/domain/entities/movie.dart'
    as _i7;
import 'package:movie_locator/features/movies/domain/entities/tv_show.dart'
    as _i17;
import 'package:movie_locator/features/movies/domain/entities/video.dart'
    as _i15;
import 'package:movie_locator/features/movies/domain/repositories/movies_repository.dart'
    as _i2;
import 'package:movie_locator/features/movies/domain/usecases/discover_movies.dart'
    as _i13;
import 'package:movie_locator/features/movies/domain/usecases/discover_tv_shows.dart'
    as _i18;
import 'package:movie_locator/features/movies/domain/usecases/get_movie_details.dart'
    as _i9;
import 'package:movie_locator/features/movies/domain/usecases/get_movie_genres.dart'
    as _i11;
import 'package:movie_locator/features/movies/domain/usecases/get_movie_videos.dart'
    as _i14;
import 'package:movie_locator/features/movies/domain/usecases/get_popular_movies.dart'
    as _i4;
import 'package:movie_locator/features/movies/domain/usecases/get_popular_tv_shows.dart'
    as _i16;
import 'package:movie_locator/features/movies/domain/usecases/get_top_rated_movies.dart'
    as _i8;
import 'package:movie_locator/features/movies/domain/usecases/get_tv_show_details.dart'
    as _i19;
import 'package:movie_locator/features/movies/domain/usecases/get_tv_show_videos.dart'
    as _i20;
import 'package:movie_locator/features/movies/domain/usecases/search_movies.dart'
    as _i10;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeMoviesRepository_0 extends _i1.SmartFake
    implements _i2.MoviesRepository {
  _FakeMoviesRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEither_1<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [GetPopularMovies].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetPopularMovies extends _i1.Mock implements _i4.GetPopularMovies {
  MockGetPopularMovies() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.MoviesRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeMoviesRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.MoviesRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, List<_i7.Movie>>> call(
          _i4.GetPopularMoviesParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue: _i5.Future<_i3.Either<_i6.Failure, List<_i7.Movie>>>.value(
            _FakeEither_1<_i6.Failure, List<_i7.Movie>>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, List<_i7.Movie>>>);
}

/// A class which mocks [GetTopRatedMovies].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetTopRatedMovies extends _i1.Mock implements _i8.GetTopRatedMovies {
  MockGetTopRatedMovies() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.MoviesRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeMoviesRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.MoviesRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, List<_i7.Movie>>> call(
          _i8.GetTopRatedMoviesParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue: _i5.Future<_i3.Either<_i6.Failure, List<_i7.Movie>>>.value(
            _FakeEither_1<_i6.Failure, List<_i7.Movie>>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, List<_i7.Movie>>>);
}

/// A class which mocks [GetMovieDetails].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetMovieDetails extends _i1.Mock implements _i9.GetMovieDetails {
  MockGetMovieDetails() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.MoviesRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeMoviesRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.MoviesRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, _i7.Movie>> call(
          _i9.GetMovieDetailsParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue: _i5.Future<_i3.Either<_i6.Failure, _i7.Movie>>.value(
            _FakeEither_1<_i6.Failure, _i7.Movie>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, _i7.Movie>>);
}

/// A class which mocks [SearchMovies].
///
/// See the documentation for Mockito's code generation for more information.
class MockSearchMovies extends _i1.Mock implements _i10.SearchMovies {
  MockSearchMovies() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.MoviesRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeMoviesRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.MoviesRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, List<_i7.Movie>>> call(
          _i10.SearchMoviesParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue: _i5.Future<_i3.Either<_i6.Failure, List<_i7.Movie>>>.value(
            _FakeEither_1<_i6.Failure, List<_i7.Movie>>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, List<_i7.Movie>>>);
}

/// A class which mocks [GetMovieGenres].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetMovieGenres extends _i1.Mock implements _i11.GetMovieGenres {
  MockGetMovieGenres() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.MoviesRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeMoviesRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.MoviesRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, List<_i12.Genre>>> call() =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
        ),
        returnValue:
            _i5.Future<_i3.Either<_i6.Failure, List<_i12.Genre>>>.value(
                _FakeEither_1<_i6.Failure, List<_i12.Genre>>(
          this,
          Invocation.method(
            #call,
            [],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, List<_i12.Genre>>>);
}

/// A class which mocks [DiscoverMovies].
///
/// See the documentation for Mockito's code generation for more information.
class MockDiscoverMovies extends _i1.Mock implements _i13.DiscoverMovies {
  MockDiscoverMovies() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.MoviesRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeMoviesRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.MoviesRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, List<_i7.Movie>>> call(
          _i13.DiscoverMoviesParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue: _i5.Future<_i3.Either<_i6.Failure, List<_i7.Movie>>>.value(
            _FakeEither_1<_i6.Failure, List<_i7.Movie>>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, List<_i7.Movie>>>);
}

/// A class which mocks [GetMovieVideos].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetMovieVideos extends _i1.Mock implements _i14.GetMovieVideos {
  MockGetMovieVideos() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.MoviesRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeMoviesRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.MoviesRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, List<_i15.Video>>> call(
          _i14.GetMovieVideosParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue:
            _i5.Future<_i3.Either<_i6.Failure, List<_i15.Video>>>.value(
                _FakeEither_1<_i6.Failure, List<_i15.Video>>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, List<_i15.Video>>>);
}

/// A class which mocks [GetPopularTvShows].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetPopularTvShows extends _i1.Mock implements _i16.GetPopularTvShows {
  MockGetPopularTvShows() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.MoviesRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeMoviesRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.MoviesRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, List<_i17.TvShow>>> call(
          _i16.GetPopularTvShowsParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue:
            _i5.Future<_i3.Either<_i6.Failure, List<_i17.TvShow>>>.value(
                _FakeEither_1<_i6.Failure, List<_i17.TvShow>>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, List<_i17.TvShow>>>);
}

/// A class which mocks [DiscoverTvShows].
///
/// See the documentation for Mockito's code generation for more information.
class MockDiscoverTvShows extends _i1.Mock implements _i18.DiscoverTvShows {
  MockDiscoverTvShows() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.MoviesRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeMoviesRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.MoviesRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, List<_i17.TvShow>>> call(
          _i18.DiscoverTvShowsParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue:
            _i5.Future<_i3.Either<_i6.Failure, List<_i17.TvShow>>>.value(
                _FakeEither_1<_i6.Failure, List<_i17.TvShow>>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, List<_i17.TvShow>>>);
}

/// A class which mocks [GetTvShowDetails].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetTvShowDetails extends _i1.Mock implements _i19.GetTvShowDetails {
  MockGetTvShowDetails() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.MoviesRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeMoviesRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.MoviesRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, _i17.TvShow>> call(
          _i19.GetTvShowDetailsParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue: _i5.Future<_i3.Either<_i6.Failure, _i17.TvShow>>.value(
            _FakeEither_1<_i6.Failure, _i17.TvShow>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, _i17.TvShow>>);
}

/// A class which mocks [GetTvShowVideos].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetTvShowVideos extends _i1.Mock implements _i20.GetTvShowVideos {
  MockGetTvShowVideos() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.MoviesRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeMoviesRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.MoviesRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, List<_i15.Video>>> call(
          _i20.GetTvShowVideosParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue:
            _i5.Future<_i3.Either<_i6.Failure, List<_i15.Video>>>.value(
                _FakeEither_1<_i6.Failure, List<_i15.Video>>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, List<_i15.Video>>>);
}
