// Mocks generated by Mockito 5.4.5 from annotations
// in movie_locator/test/features/movies/domain/usecases/get_popular_movies_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:movie_locator/core/errors/failures.dart' as _i5;
import 'package:movie_locator/features/movies/domain/entities/genre.dart'
    as _i8;
import 'package:movie_locator/features/movies/domain/entities/movie.dart'
    as _i6;
import 'package:movie_locator/features/movies/domain/entities/tv_show.dart'
    as _i7;
import 'package:movie_locator/features/movies/domain/repositories/movies_repository.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [MoviesRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockMoviesRepository extends _i1.Mock implements _i3.MoviesRepository {
  MockMoviesRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.Movie>>> getPopularMovies(
          {int? page = 1}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPopularMovies,
          [],
          {#page: page},
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, List<_i6.Movie>>>.value(
            _FakeEither_0<_i5.Failure, List<_i6.Movie>>(
          this,
          Invocation.method(
            #getPopularMovies,
            [],
            {#page: page},
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<_i6.Movie>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.Movie>>> getTopRatedMovies(
          {int? page = 1}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTopRatedMovies,
          [],
          {#page: page},
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, List<_i6.Movie>>>.value(
            _FakeEither_0<_i5.Failure, List<_i6.Movie>>(
          this,
          Invocation.method(
            #getTopRatedMovies,
            [],
            {#page: page},
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<_i6.Movie>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.Movie>>> getNowPlayingMovies(
          {int? page = 1}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getNowPlayingMovies,
          [],
          {#page: page},
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, List<_i6.Movie>>>.value(
            _FakeEither_0<_i5.Failure, List<_i6.Movie>>(
          this,
          Invocation.method(
            #getNowPlayingMovies,
            [],
            {#page: page},
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<_i6.Movie>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.Movie>>> getUpcomingMovies(
          {int? page = 1}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUpcomingMovies,
          [],
          {#page: page},
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, List<_i6.Movie>>>.value(
            _FakeEither_0<_i5.Failure, List<_i6.Movie>>(
          this,
          Invocation.method(
            #getUpcomingMovies,
            [],
            {#page: page},
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<_i6.Movie>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.Movie>> getMovieDetails(
          int? movieId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMovieDetails,
          [movieId],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, _i6.Movie>>.value(
            _FakeEither_0<_i5.Failure, _i6.Movie>(
          this,
          Invocation.method(
            #getMovieDetails,
            [movieId],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.Movie>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.Movie>>> searchMovies(
    String? query, {
    int? page = 1,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchMovies,
          [query],
          {#page: page},
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, List<_i6.Movie>>>.value(
            _FakeEither_0<_i5.Failure, List<_i6.Movie>>(
          this,
          Invocation.method(
            #searchMovies,
            [query],
            {#page: page},
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<_i6.Movie>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i7.TvShow>>> getPopularTvShows(
          {int? page = 1}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPopularTvShows,
          [],
          {#page: page},
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, List<_i7.TvShow>>>.value(
                _FakeEither_0<_i5.Failure, List<_i7.TvShow>>(
          this,
          Invocation.method(
            #getPopularTvShows,
            [],
            {#page: page},
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<_i7.TvShow>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i7.TvShow>>> getTopRatedTvShows(
          {int? page = 1}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTopRatedTvShows,
          [],
          {#page: page},
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, List<_i7.TvShow>>>.value(
                _FakeEither_0<_i5.Failure, List<_i7.TvShow>>(
          this,
          Invocation.method(
            #getTopRatedTvShows,
            [],
            {#page: page},
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<_i7.TvShow>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i7.TvShow>>> getOnTheAirTvShows(
          {int? page = 1}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getOnTheAirTvShows,
          [],
          {#page: page},
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, List<_i7.TvShow>>>.value(
                _FakeEither_0<_i5.Failure, List<_i7.TvShow>>(
          this,
          Invocation.method(
            #getOnTheAirTvShows,
            [],
            {#page: page},
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<_i7.TvShow>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i7.TvShow>> getTvShowDetails(int? tvId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTvShowDetails,
          [tvId],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, _i7.TvShow>>.value(
            _FakeEither_0<_i5.Failure, _i7.TvShow>(
          this,
          Invocation.method(
            #getTvShowDetails,
            [tvId],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i7.TvShow>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i7.TvShow>>> searchTvShows(
    String? query, {
    int? page = 1,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchTvShows,
          [query],
          {#page: page},
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, List<_i7.TvShow>>>.value(
                _FakeEither_0<_i5.Failure, List<_i7.TvShow>>(
          this,
          Invocation.method(
            #searchTvShows,
            [query],
            {#page: page},
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<_i7.TvShow>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i8.Genre>>> getMovieGenres() =>
      (super.noSuchMethod(
        Invocation.method(
          #getMovieGenres,
          [],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, List<_i8.Genre>>>.value(
            _FakeEither_0<_i5.Failure, List<_i8.Genre>>(
          this,
          Invocation.method(
            #getMovieGenres,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<_i8.Genre>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i8.Genre>>> getTvGenres() =>
      (super.noSuchMethod(
        Invocation.method(
          #getTvGenres,
          [],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, List<_i8.Genre>>>.value(
            _FakeEither_0<_i5.Failure, List<_i8.Genre>>(
          this,
          Invocation.method(
            #getTvGenres,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<_i8.Genre>>>);
}
